// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sheep.SiteV2.Api.Data;
using System;

namespace Sheep.SiteV2.Api.Migrations
{
    [DbContext(typeof(SheepSiteV2Context))]
    partial class SheepSiteV2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Sheep.SiteV2.Api.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("sheepDOB");

                    b.Property<string>("sheepGender");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Sheep.SiteV2.Api.Models.Pregnancy", b =>
                {
                    b.Property<int>("pregnancyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("actBirth");

                    b.Property<string>("conceptionDate");

                    b.Property<string>("estBirth");

                    b.Property<int>("numberOfBabies");

                    b.Property<int>("pAnimalId");

                    b.Property<string>("pregnancyComment");

                    b.HasKey("pregnancyID");

                    b.ToTable("Pregnancies");
                });

            modelBuilder.Entity("Sheep.SiteV2.Api.Models.Treatment", b =>
                {
                    b.Property<int>("treatmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("tAnimalId");

                    b.Property<string>("treatmentComment");

                    b.Property<DateTime>("treatmentDate");

                    b.Property<string>("treatmentDosage");

                    b.Property<string>("treatmentName");

                    b.HasKey("treatmentID");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Sheep.SiteV2.Api.Models.Vaccine", b =>
                {
                    b.Property<int>("vaccineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("vAnimalId");

                    b.Property<string>("vaccineComment");

                    b.Property<DateTime>("vaccineDate");

                    b.Property<string>("vaccineDosage");

                    b.Property<string>("vaccineName");

                    b.HasKey("vaccineID");

                    b.ToTable("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
